common/models/Customers.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use faryshta\base\EnumTrait;
use yii\db\Expression;
use faryshta\validators\EnumValidator;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "customers".
 *
 * @property integer $id
 * @property string $email
 * @property string $phone
 * @property string $address
 * @property string $password
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $province
 * @property string $district
 * @property string $first_name
 * @property string $last_name
 * @property string $ship_address
 *
 * @property Transactions[] $transactions
 */
class Customers extends \yii\db\ActiveRecord implements IdentityInterface
{
  /**
   * @inheritdoc
   */
  public $password_confirm;
  public static function tableName()
  {
    return 'customers';
  }
  public function behaviors()
  {
    return [
      [
        'class' => TimestampBehavior::className(),
        'createdAtAttribute' => 'created_at',
        'updatedAtAttribute' => 'updated_at'
      ],
      'timestamp' => [
        'class' => 'yii\behaviors\TimestampBehavior',
        'attributes' => [
          \yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
          \yii\db\ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
        ],
      ]
    ];
  }
  public function fields()
  {
    $fields=  parent::fields(); // TODO: Change the autogenerated stub
    unset($fields['password']);
    return $fields;

  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['first_name', 'last_name', 'email', 'password','password_confirm','address','province'], 'required'],
      [[ 'email', 'address','ship_address'], 'string', 'max' => 255],
      [[ 'password', 'province', 'district', 'first_name', 'last_name'], 'string', 'max' => 50],
      ['password_confirm', 'compare', 'compareAttribute'=>'password', 'message'=>"Passwords don't match" ],
      [['phone'], 'string', 'max' => 20],
      [['email'], 'unique'],
      ['email', 'unique'],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'email' => 'Email',
      'phone' => 'Phone',
      'address' => 'Address',
      'password' => 'Password',
      'created_at' => 'Created At',
      'updated_at' => 'Updated At',
      'province' => 'Province',
      'district' => 'District',
      'first_name' => 'Tên',
      'last_name' => 'Họ',
    ];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getTransactions()
  {
    return $this->hasMany(Transactions::className(), ['customer_id' => 'id']);
  }
  public function beforeSave($insert)
  {
    $this->setPassword($this->password);

    return parent::beforeSave($insert);
  }

  public function setPassword($password)
  {
    $this->password = Yii::$app->security->generatePasswordHash($password);
  }
  public static function findIdentity($id)
  {

    return static::findOne(['id' => $id]);

    // TODO: Implement findIdentity() method.
  }

  public static function findIdentityByAccessToken($token, $type = null)
  {
    // TODO: Implement findIdentityByAccessToken() method.
  }

  public function getId()
  {

    return $this->getPrimaryKey();
  }

  public function getAuthKey()
  {
    // TODO: Implement getAuthKey() method.
  }

  public function validateAuthKey($authKey)
  {
    // TODO: Implement validateAuthKey() method.
  }
  public static function findByEmail($email)
  {
    return static::findOne(['email' => $email]);

  }
  public function validatePassword($password)
  {
    return Yii::$app->security->validatePassword($password, $this->password);
  }

}

backend/controllers/CustomersController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Customers;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CustomersController implements the CRUD actions for Customers model.
 */
class CustomersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Customers models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Customers::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Customers model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Customers model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Customers();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Customers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Customers model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Customers model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Customers the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customers::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/HomeController.php
<?php

namespace backend\controllers;

class HomeController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

}

frontend/controllers/CustomersController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Customers;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\models\LoginForm;
use yii\filters\AccessControl;

/**
 * CustomersController implements the CRUD actions for Customers model.
 */
class CustomersController extends AppController
{
  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['login', 'logout','get-user'],
        'rules' => [
          [
            'allow' => true,
            'actions' => ['login'],
            'roles' => ['?'],
          ],
          [
            'allow' => true,
            'actions' => ['get-user','logout'],
            'roles' => ['@'],
          ],
        ],
      ]
    ];
  }


  /**
   * Displays a single Customers model.
   * @param integer $id
   * @return mixed
   */
  public function actionView($id)
  {
    return $this->render('view', [
      'model' => $this->findModel($id),
    ]);
  }

  /**
   * Creates a new Customers model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionRegister(){
    $model = new Customers();
    return $this->render('register',[
      'model'=>$model
    ]);
  }
  public function actionCreate()
  {
    $model = new Customers();

    if ($model->load(Yii::$app->request->post()) && $model->save()) {
      Yii::$app->user->switchIdentity($model);
      return $this->redirect(['home/index']);
    } else {
      return $this->render('register', [
        'model' => $model,
      ]);
    }
  }

  /**
   * Updates an existing Customers model.
   * If update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
//    $model = $this->findModel($id);
//
//    if ($model->load(Yii::$app->request->post()) && $model->save()) {
//      return $this->redirect(['view', 'id' => $model->id]);
//    } else {
//      return $this->render('update', [
//        'model' => $model,
//      ]);
//    }
  }
  public function actionLogin(){
    $this->layout = 'home_layout';
    $model = new LoginForm();
    if ($model->load(Yii::$app->request->post()) && $model->login()) {
      return $this->redirect(['home/index']);
    } else {
      return $this->render('login', [
        'model' => $model,
      ]);
    }
  }
  public function actionGetUser(){
    $customer = Yii::$app->user->identity;
    $response = Yii::$app->response;
    $response->format = \yii\web\Response::FORMAT_JSON;
    $response->data = ['customer'=>$customer->toArray()];

    return $response;
  }


  /**
   * Finds the Customers model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Customers the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = Customers::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('The requested page does not exist.');
    }
  }
  public function actionLogout()
  {
    Yii::$app->user->logout();

    return $this->goHome();
  }
}

frontend/views/customers/_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Customers */
/* @var $form yii\widgets\ActiveForm */

?>

<?php $form = ActiveForm::begin(
  [
    'action'=> Url::to(['customers/create']),
    'fieldConfig' => [
      'options' => [
        'tag'=>'div',
        'class'=>'input-box register-customer'
      ],
    ]
  ]
); ?>
  <ul>
    <li>
      <div class="customer-name">
        <?= $form->field($model, 'first_name')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Tên'. Html::tag('span', '*',['class'=>'required']),['class'=>'label-class']); ?>
        <?= $form->field($model, 'last_name')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Họ'. Html::tag('span', '*',['class'=>'required']),['class'=>'label-class']); ?>
      </div>
    </li>
    <li>
      <?= $form->field($model, 'email')
        ->textInput(['maxlength' => true,'class' => 'input-text'])
        ->label('Email'. Html::tag('span', '*',['class'=>'required']),['class'=>'label-class']);
      ?>
      <?= $form->field($model, 'phone')
        ->textInput(['maxlength' => true,'class' => 'input-text'])
        ->label('Số điện thoại',['class'=>'label-class']); ?>
    </li>
    <li>
      <?= $form->field($model, 'password')->passwordInput(['maxlength' => true,'class' => 'input-text'])
        ->label('Mật khẩu'. Html::tag('span', '*',['class'=>'required']),['class'=>'label-class']); ?>
      <?= $form->field($model, 'password_confirm')->passwordInput(['maxlength' => true,'class' => 'input-text'])->label('Xác nhận mật khẩu'. Html::tag('span', '*',['class'=>'required']). Html::tag('br'),['class'=>'label-class']); ?>
    </li>
    <li>
      <?= $form->field($model, 'province')->textInput(['maxlength' => true,'class' => 'input-text'])
        ->label('Tỉnh/Thành phố'.Html::tag('span', '*',['class'=>'required']),['class'=>'label-class']); ?>
      <?= $form->field($model, 'district')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Huyện/Quận'. Html::tag('span', '*',['class'=>'required']). Html::tag('br'),['class'=>'label-class']); ?>
    </li>
    <li>
      <?= $form->field($model, 'address',['template' => '{label} <br> {input}{error}{hint}','options'=>['tag'=>false]])
        ->textInput(['maxlength' => true,'class' => 'input-text'])
        ->label('Địa chỉ',['class'=>'label-class']);
      ?>

    </li>
    <li>
      <?= $form->field($model, 'ship_address',['template' => '{label} <br> {input}{error}{hint}','options'=>['tag'=>false]])
        ->textInput(['maxlength' => true,'class' => 'input-text'])
        ->label('Địa chỉ giao hàng',['class'=>'label-class']); ?>
    </li>
    <li><span class="require"><em class="required">* </em>Required Fields</span>
      <div class="buttons-set">
        <button type="submit" title="Submit" class="button submit"> <span> Submit </span> </button>
      </div></li>
  </ul>
<?php ActiveForm::end(); ?>

frontend/views/customers/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Customers */

$this->title = 'Create Customers';
$this->params['breadcrumbs'][] = ['label' => 'Customers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customers-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/customers/login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Customers */
/* @var $form yii\widgets\ActiveForm */

?>
<section class="main-container col1-layout wow bounceInUp animated">
  <div class="main container">
    <div class="account-login">
      <div class="page-title">
        <h2>Đăng nhập hoặc tạo tài khoản</h2>
      </div>
      <fieldset class="col2-set">
        <legend>Đăng nhập hoặc tạo tài khoản</legend>
        <div class="col-1 new-users"><strong>Tạo tài khoản</strong>
          <div class="content">
<!--            <p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>-->
            <div class="buttons-set">
              <button class="button create-account"><span>Tạo tài khoản</span></button>
            </div>
          </div>
        </div>
        <?php $form = ActiveForm::begin(
          [
            'fieldConfig' => [
              'options' => [
                'tag'=>false
              ],
            ]
          ]
        ); ?>
        <div class="col-2 registered-users">
          <div class="content">
            <ul class="form-list">
              <li>
                <?= $form->field($model, 'email')
                  ->textInput(['maxlength' => true,'class' => 'input-text'])
                  ->label('Email'. Html::tag('span', '*',['class'=>'required']),['class'=>'label-class']);
                ?>
              </li>
              <li>
                <?= $form->field($model, 'password')->passwordInput(['maxlength' => true,'class' => 'input-text'])
                  ->label('Mật khẩu'. Html::tag('span', '*',['class'=>'required']),['class'=>'label-class']); ?>
              </li>
            </ul>
            <p class="required">* Trường bắt buộc</p>
            <div class="buttons-set">
              <button id="send2" name="send" type="submit" class="button login"><span>Đăng nhập</span></button>
<!--              <a class="forgot-word" href="#">Forgot Your Password?</a> </div>-->
          </div>
        </div>
        <?php ActiveForm::end(); ?>
      </fieldset>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>
</section>

frontend/views/customers/register.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <ul>
          <li class="home"> <a title="Go to Home Page" href="<?=Url::to(['home/index'])?>">Home</a><span>&mdash;›</span></li>
          <li class="category13"><strong>Tạo tài khoản</strong></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- Breadcrumbs End -->
<!-- Main Container -->
<div class="main-container col2-right-layout wow bounceInUp animated">
  <div class="main container">
    <div class="row">
      <section class="col-main col-sm-9">
        <div class="page-title">
          <h2>Đăng ký tài khoản</h2>
        </div>
        <div class="static-contain">
          <fieldset class="group-select">
            <ul>
              <li id="billing-new-address-form">
                <fieldset>
                  <legend>Đăng ký tài khoản</legend>
                  <input type="hidden" name="billing[address_id]" id="billing:address_id">
                  <?= $this->render('_form', [
                    'model' => $model,
                  ]) ?>
                </fieldset>
              </li>
            </ul>
          </fieldset>
        </div>
      </section>
<!--      <aside class="col-right sidebar col-sm-3">-->
<!--        <div class="block block-company">-->
<!--          <div class="block-title">Company </div>-->
<!--          <div class="block-content">-->
<!--            <ol id="recently-viewed-items">-->
<!--              <li class="item odd"><a href="about_us.html">About Us</a></li>-->
<!---->
<!--              <li class="item  odd"><a href="#">Terms of Service</a></li>-->
<!--              <li class="item even"><a href="#">Search Terms</a></li>-->
<!--              <li class="item last"><strong>Contact Us</strong></li>-->
<!--            </ol>-->
<!--          </div>-->
<!--        </div>-->
<!--      </aside>-->
    </div>
  </div>
</div>
<!-- Main Container End -->

frontend/views/customers/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Customers */

$this->title = 'Update Customers: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Customers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="customers-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/customers/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Customers */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Customers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customers-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'email:email',
            'phone',
            'address',
            'password',
            'created_at',
            'updated_at',
            'province',
            'district',
            'first_name',
            'last_name',
        ],
    ]) ?>

</div>