backend/controllers/HomeController.php
<?php

namespace backend\controllers;

class HomeController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

}

frontend/controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: phan-kiet
 * Date: 5/19/16
 * Time: 10:24 PM
 */

namespace frontend\controllers;


use common\models\Orders;
use common\models\Products;
use common\models\Transactions;
use yii\helpers\Url;
use yii\web\Controller;
use Yii;
use yii\db\Transaction;
use yii\db\Query;


class CartController extends AppController
{
  public function actionCheckout()
  {
    $tran = new Transactions();

    if (Yii::$app->request->post()) {
      $session = Yii::$app->session;
      $data_carts = $session['cart'];
      $transaction_data = isset(Yii::$app->request->post()['Transactions']) ? Yii::$app->request->post()['Transactions'] : [];
      $connection = \Yii::$app->db;
      $transaction = $connection->beginTransaction();
      try {
        $detailCarts = $this->getDetailCart($data_carts);
        $tran->first_name = $transaction_data['first_name'];
        if($this->curent_user){
          $tran->customer_id = $this->curent_user->id;
        }
        $tran->province = $transaction_data['province'];
        $tran->user_email = $transaction_data['user_email'];
        $tran->last_name = $transaction_data['last_name'];
        $tran->district = $transaction_data['district'];
        $tran->user_phone = $transaction_data['user_phone'];
        $tran->address = $transaction_data['address'];
        $tran->amount = $detailCarts['amount'];

        if($tran->save()){
          foreach ($detailCarts['product'] as $product) {
            if (intval($data_carts[$product->id]['count']) > 0) {
              $order = new Orders();
              $order->product_id =  $product->id;
              $order->qty =  $data_carts[$product->id]['count'];
              $order->unit_price =  $product->price;
              $order->discount =  $product->discount;
              $order->size =  $data_carts[$product->id]['size'];
              $order->note =  $data_carts[$product->id]['note'];
              $order->discount =  $product->discount;
              $order->amount =   $product->price - $product->discount;
              $tran->link('orders', $order);
            }

          }
          $session->remove('cart');
        }
        $transaction->commit();

        return $this->redirect(['message']);
      } catch (\Exception $e) {
        $transaction->rollBack();
        throw $e;
      }
    }else{
      return $this->render('checkout',['model'=>$tran]);
    }

  }
  public function actionView(){
    return $this->render('view');
  }
  public function actionUpdateCart()
  {
    if(Yii::$app->request->post() && isset(Yii::$app->request->post()['cart'])){
      $carts = Yii::$app->request->post()['cart'];
      $session = Yii::$app->session;
      $temp_cart = $session['cart'];
      foreach(Yii::$app->request->post()['cart'] as $key => $cart){
        $temp_cart[intval($key)]['count'] = intval($cart['qty']);
        $temp_cart[intval($key)]['size'] = $cart['size'];
        $temp_cart[intval($key)]['note'] = $cart['note'];
      }
      $session['cart'] = $temp_cart;

    }
    return $this->redirect(Yii::$app->request->referrer);

  }
  public function actionMessage(){
    return $this->render('message');
  }

  private function getDetailCart($data_carts)
  {
    $product_ids = array_keys($data_carts);
    $items = Products::findAll($product_ids);
    $amount = 0;
    foreach ($items as $product) {
      if (intval($data_carts[$product->id]['count']) > 0) {
        $amount += ($product->price - $product->discount) * intval($data_carts[$product->id]['count']);

      }
    }
    return ['amount' => $amount, 'product' => $items];

  }


}

frontend/views/cart/_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use yii\helpers\Url;
use frontend\helper\FrontEndHelper;
$yourCart = FrontEndHelper::printCart();


/* @var $this yii\web\View */
/* @var $model common\models\Customers */
/* @var $form yii\widgets\ActiveForm */

?>

<?php $form = ActiveForm::begin(
  [
    'fieldConfig' => [
      'options' => [
        'tag'=>'div',
        'class'=>'input-box'
      ],
    ]
  ]
); ?>

    <input type="hidden" name="_csrf" value="<?= Yii::$app->request->getCsrfToken() ?>"/>
    <!-- BEGIN CART COLLATERALS -->
    <div class="cart-collaterals row">
      <div class="col-sm-8">
        <div class="shipping">
          <h3>Thông tin khách hàng</h3>
          <div class="col-sm-12">
            <input type="checkbox" value="1" id="use_customer_info"> Sử dụng thông tin bạn đã đăng ký
            <br>
          </div>
          <div class="shipping-form">

            <div class="col-sm-6">

              <ul class="form-list">
                <li>
                  <?= $form->field($model, 'first_name')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Tên'. Html::tag('span', '*',['class'=>'required']),['class'=>'']); ?>
<!--                  <label for="postcode">Họ</label>-->
<!--                  <div class="input-box">-->
<!--                    <input type="text" name="Transactions[first_name]" class="input-text validate-postcode">-->
<!--                  </div>-->
                </li>
                <li>
                  <?= $form->field($model, 'province')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Tỉnh/thành phố'. Html::tag('span', '*',['class'=>'required']),['class'=>'']); ?>
                </li>
                <li>
                  <?= $form->field($model, 'user_email')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Email'. Html::tag('span', '*',['class'=>'required']),['class'=>'']); ?>
                </li>
              </ul>
            </div>
            <div class="col-sm-6">
              <ul class="form-list">
                <li>
                  <?= $form->field($model, 'last_name')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Họ'. Html::tag('span', '*',['class'=>'required']),['class'=>'']); ?>

                </li>
                <li>
                  <?= $form->field($model, 'district')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Quận/Huyện'. Html::tag('span', '*',['class'=>'required']),['class'=>'']); ?>
                </li>
                <li>
                  <?= $form->field($model, 'user_phone')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Điện thoại'. Html::tag('span', '*',['class'=>'required']),['class'=>'']); ?>
                </li>
              </ul>
            </div>
            <div class="col-sm-12">
              <ul class="form-list">
                <li>
                  <?= $form->field($model, 'address')->textInput(['maxlength' => true,'class' => 'input-text'])->label('Địa chỉ'. Html::tag('span', '*',['class'=>'required']),['class'=>'']); ?>
                </li>

              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="totals col-sm-4">
        <h3>Tổng giá trị đơn hàng</h3>
        <div class="inner">
          <table class="table shopping-cart-table-total" id="shopping-cart-totals-table">

            <tfoot>
            <tr>
              <td colspan="1" class="a-left"><strong>Thành tiền</strong></td>
              <td class="a-right"><strong><span
                    class="price">$<?= FrontEndHelper::getPriceCart($yourCart) ?></span></strong></td>
            </tr>
            </tfoot>
          </table>
          <ul class="checkout">
            <li>
              <button class="button btn-proceed-checkout" title="Proceed to Checkout" type="submit">
                <span>Đặt hàng</span>
              </button>
            </li>

          </ul>
        </div>
        <!--inner-->

      </div>
    </div>

<?php ActiveForm::end(); ?>

frontend/views/cart/checkout.php
<?php
use frontend\helper\FrontEndHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\AppHelper;

$yourCart = FrontEndHelper::printCart();
?>
<section class="main-container col1-layout wow bounceInUp animated">
  <div class="main container">
    <div class="col-main">

      <div class="cart">
        <div class="page-title">
          <h2>Xác nhận đơn hàng</h2>
        </div>
        <div class="table-responsive">


          <table class="data-table cart-table" id="shopping-cart-table">
            <thead>
            <tr class="first last">
              <th rowspan="1">&nbsp;</th>
              <th rowspan="1"><span class="nobr">Tên sản phẩm</span></th>
              <th rowspan="1" class="hidden-phone"></th>
              <th colspan="1" class="a-center"><span class="nobr">Giá gốc</span></th>
              <th rowspan="1" class="hidden-phone"><span class="nobr">Giảm giá</span></th>
              <th class="a-center " rowspan="1">Số lượng</th>
              <th colspan="1" class="a-center">Thành tiền</th>
            </tr>
            </thead>
            <tfoot>
            <tr class="first last">
              <td class="a-right last" colspan="8">
                <button onclick="setLocation('<?= Url::to(['home/index']) ?>')" class="button btn-continue" title="Continue Shopping" type="button">
                  <span>Continue Shopping</span>
                </button>
              </td>
            </tr>
            </tfoot>
            <tbody>
            <?php foreach ($yourCart as $cart): ?>
              <?php $item = $cart['item'];
              $images = $item->images;
              ?>
              <tr class="first odd">
                <td class="image">
                  <a href="<?= Url::to(['products/view', "id" => $item->id]) ?>" title="<?= $item->name ?>"
                     class="product-image">
                    <?= Html::img('@web/' . FrontEndHelper::imageUrl($images[0], $images[0]->file_path), [
                      'alt' => $item->name,
                      'width' => "75"
                    ]) ?>
                  </a>
                </td>
                <td><h2 class="product-name"><a
                      href="<?= Url::to(['products/view', "id" => $item->id]) ?>"><?= $item->name ?></a></h2></td>
                <td class="a-center hidden-table"><a title="Edit item parameters" class="edit-bnt" href="#"></a>
                </td>
                <td class="a-center hidden-table"><a class="link-wishlist1 use-ajax"
                                                     href="#">$<?= AppHelper::formatPrice($item->price) ?></a></td>
                <td class="a-center hidden-table"><span class="cart-price"> <span
                      class="price">$<?= AppHelper::formatPrice($item->discount) ?></span> </span></td>
                <td class="a-center movewishlist">
                  <?= $cart['count'] ?>
                </td>
                <td class="a-center movewishlist">
                  <span class="cart-price">
                    <span class="price">$<?= AppHelper::formatPrice($cart['count'] * ($item->price - $item->discount)) ?></span>
                  </span>
                </td>

              </tr>
            <?php endforeach; ?>
            </tbody>
          </table>
        </div>
        <?= $this->render('_form',['model'=>$model]) ?>

      </div>


    </div>
  </div>
</section>

frontend/views/cart/message.php
<?php
use frontend\helper\FrontEndHelper;
?>

<div class="main-container col2-right-layout wow bounceInUp animated">
  <div class="main container">
    <div class="row">
      <div class="col-main col-sm-9">
        <div class="my-account">
          <div class="page-title">
            <h2>Đặt hàng thành công</h2>
          </div>
          <div class="dashboard">
            <div class="welcome-msg">
              <p>Cảm ơn bạn đã mua hàng tại shop của chúng tôi. Chúng tôi sẽ giao hàng cho bạn sớm nhất có thể</p>
              <a style="color: #00CC00" href="<?=\yii\helpers\Url::home() ?>" > Quay về trang chủ</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

frontend/views/cart/view.php
<?php
use frontend\helper\FrontEndHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\AppHelper;
$yourCart = FrontEndHelper::printCart();
?>
<section class="main-container col1-layout wow bounceInUp animated">
  <div class="main container">
    <div class="col-main">
      <form method="post" action="<?= Url::to(['cart/update-cart']) ?>">
        <div class="cart">
          <div class="page-title">
            <h2>Shopping Cart</h2>
          </div>
          <div class="table-responsive">

            <input type="hidden" name="_csrf" value="<?= Yii::$app->request->getCsrfToken() ?>"/>
            <fieldset>
              <table class="data-table cart-table" id="shopping-cart-table">
                <thead>
                <tr class="first last">
                  <th rowspan="1">&nbsp;</th>
                  <th rowspan="1"><span class="nobr">Tên sản phẩm</span></th>
                  <th colspan="1" class="a-center"><span class="nobr">Giá gốc(VND)</span></th>
                  <th rowspan="1" class="hidden-phone"><span class="nobr">Giảm giá(VND)</span></th>
                  <th class="a-center " rowspan="1">Số lượng</th>
                  <th class="a-center " rowspan="1">Size</th>
                  <th class="a-center " rowspan="1">Ghi chú</th>
                  <th colspan="1" class="a-center">Thành tiền(VND)</th>
                  <th class="a-center" rowspan="1">&nbsp;</th>
                </tr>
                </thead>
                <tfoot>
                <tr class="first last">
                  <td class="a-right last" colspan="9">
                    <button onclick="setLocation('<?= Url::to(['home/index']) ?>')" class="button btn-continue" title="Continue Shopping" type="button">
                      <span>Tiếp tục mua hàng</span>
                    </button>
                    <button onclick="setLocation('<?= Url::to(['home/index']) ?>')" class="button" title="Continue Shopping" type="submit">
                      <span>Cập nhật giỏ hàng</span>
                    </button>
                    <button onclick="window.location.href = baseUrl + '/cart/checkout'"  class="button" title="Clear Cart" type="button">
                      <span>Đặt hàng</span>
                    </button>
                    <button onclick="window.location.href = baseUrl + '/products/clear-cart'" id="empty_cart_button" class="button" title="Clear Cart" type="button">
                      <span>Hủy giỏ hàng</span>
                    </button>
                  </td>
                </tr>
                </tfoot>
                <tbody>
                <?php foreach ($yourCart as $cart): ?>
                  <?php $item = $cart['item'];
                  $images = $item->images;
                  ?>
                  <tr class="first odd">
                    <td class="image">
                      <a href="<?= Url::to(['products/view', "id" => $item->id]) ?>" title="<?= $item->name ?>"
                         class="product-image">
                        <?= Html::img('@web/' . FrontEndHelper::imageUrl($images[0], $images[0]->file_path), [
                          'alt' => $item->name,
                          'width' => "75"
                        ]) ?>
                      </a>
                    </td>
                    <td><h2 class="product-name"><a
                          href="<?= Url::to(['products/view', "id" => $item->id]) ?>"><?= $item->name ?></a></h2></td>

                    <td class="a-center hidden-table price"data-value = "<?=$item->price?>" >
                      <a class="link-wishlist1 use-ajax" href="#"><?= AppHelper::formatPrice($item->price) ?></a>
                    </td>
                    <td class="a-center hidden-table discount" data-value = "<?=$item->discount?>">
                      <span class="cart-price">
                        <?= AppHelper::formatPrice($item->discount) ?>
                      </span>
                    </td>
                    <td class="a-center movewishlist">
                      <input maxlength="12" class="input-text qty" title="Qty" size="4" value="<?= $cart['count'] ?>" name="cart[<?= $item->id ?>][qty]">
                    </td>
                    <td class="a-center movewishlist">
                      <input maxlength="12" class="input-text qty" title="Size" size="4" value="<?= $cart['size'] ?>" name="cart[<?= $item->id ?>][size]">
                    </td>
                    <td class="a-center movewishlist">
                      <input maxlength="12" class="input-text qty" title="Qty" size="4" value="<?= $cart['note'] ?>" name="cart[<?= $item->id ?>][note]">
                    </td>
                    <td class="a-center movewishlist"><span class="cart-price"> <span
                          class="price">$<?= AppHelper::formatPrice($cart['count']*($item->price - $item->discount))?></span> </span></td>
                    <td class="a-center last">
                      <a class="button remove-item" title="Remove item" href="<?= Url::to(['products/remove-cart', "id" => $item->id]) ?>"><span><span>Remove item</span></span>
                      </a>
                    </td>
                  </tr>
                <?php endforeach; ?>
                </tbody>
              </table>
            </fieldset>
          </div>
          <!-- BEGIN CART COLLATERALS -->


          <!--cart-collaterals-->

        </div>

      </form>
    </div>
  </div>
</section>